module.exports = [
  {
    id: "rosemary",
    name: "Rosemary Bietendorf",
    title: "Owner, Personal & Group Trainer",
    image: "/images/rosemary-bietendorf.webp",
    alt: "Rosemary Bietendorf, owner and personal trainer at The Gym of Tucson",
    imageWidth: 600,
    imageHeight: 750,
    instagram: "https://www.instagram.com/thecoach_rose/",
    instagramHandle: "@thecoach_rose",
    facebook: "https://www.facebook.com/rbietendorf",
    specialties: ["Personal Training", "Nutrition", "Strength Training", "Powerlifting Coaching", "Weight Loss"],
    certifications: [
      "ACE CPT",
      "ACE Nutrition Specialist",
      "Iron Athlete Certification",
      "Pain-Free Performance Certification",
      "Barbell Rehab Certification",
      "Programming Around Pain Certification",
    ],
    bio: "With 16 years under my belt as a personal trainer, I've had the honor of guiding everyone from young D1 athletes to vibrant 81-year-old great-grandmothers on their fitness journeys. Powerlifting became my latest passion, coaching my inaugural meet in 2021 and being completely captivated by its spirit.",
    passion: "The core of my drive lies in witnessing my clients' transformations — seeing them gain confidence, achieve their personal bests, and often, surprise even themselves with their capabilities.",
    community: "Beyond training, I cherish being part of my clients' fitness narratives, celebrating their milestones, and contributing to a community of empowered and driven individuals. Ready to elevate your fitness game?",
    schema: {
      jobTitle: "Owner & Personal Trainer",
      sameAs: ["https://www.instagram.com/thecoach_rose/"],
    },
  },
  {
    id: "dustin",
    name: "Dustin Schroeder",
    title: "Personal Trainer, Physical Therapist Assistant",
    image: "/images/dustin-schroeder.webp",
    alt: "Dustin Schroeder, personal trainer and physical therapist at The Gym of Tucson",
    imageWidth: 600,
    imageHeight: 750,
    instagram: "https://www.instagram.com/dustinschroeder1/",
    instagramHandle: "@dustinschroeder1",
    facebook: "https://www.facebook.com/dustin.schroeder.503",
    specialties: ["Athletic Training", "Injury Prevention", "Rehabilitation"],
    certifications: [
      "B.S. Exercise Science",
      "Licensed PTA",
      "USSF D License",
    ],
    bio: "As a personal trainer and a physical therapist assistant, my unique blend of skills enables me to elevate athletic performance while prioritizing injury prevention and rehabilitation.",
    passion: "Fuelled by a sports background, I'm dedicated to mentoring young athletes and educating people on injury-free fitness journeys.",
    community: "Off-duty, you'll find me on the soccer field, globetrotting, or catching the latest sports game, contributing to a lively community built on shared love for fitness and sports.",
    schema: {
      jobTitle: "Personal Trainer & Physical Therapist Assistant",
      sameAs: ["https://www.instagram.com/dustinschroeder1/"],
    },
  },
  {
    id: "kristen",
    name: "Kristen Fitzpatrick",
    title: "Personal Trainer, Group Fitness Coach, Nutrition Coach",
    image: "/images/kristen-fitz.webp",
    alt: "Kristen Fitzpatrick, personal trainer and nutrition coach at The Gym of Tucson",
    imageWidth: 600,
    imageHeight: 750,
    instagram: "https://www.instagram.com/coach_kfitz/",
    instagramHandle: "@coach_kfitz",
    facebook: "https://www.facebook.com/kristen.doyle.315",
    specialties: ["Personal Training", "Nutrition Coaching", "Emotional Support"],
    certifications: [
      "NASM CPT",
      "NASM Nutrition Specialist",
      "Pain-Free Performance Certification",
      "Programming Around Pain Certification",
    ],
    bio: "As a certified personal trainer and nutrition coach, I channel my decade-long fitness enthusiasm and social work background into holistic wellness for my clients.",
    passion: "Driven by the transformative power of self-care, I'm devoted to making fitness a positive, enriching part of your life.",
    community: "When I'm not coaching, you'll find me weightlifting, strumming my guitar, capturing moments through my lens, or enjoying time with loved ones, nourishing a vibrant community of health and wellness.",
    schema: {
      jobTitle: "Personal Trainer & Nutrition Coach",
      sameAs: ["https://www.instagram.com/coach_kfitz/"],
    },
  },
  {
    id: "david",
    name: "David Skolnik",
    title: "DPT, Personal Trainer, Certified Powerlifting Coach",
    image: "/images/david-skolnik.webp",
    alt: "David Skolnik, DPT and certified powerlifting coach at The Gym of Tucson",
    imageWidth: 600,
    imageHeight: 750,
    instagram: "https://www.instagram.com/dr.davidskolnik.dpt/",
    instagramHandle: "@dr.davidskolnik.dpt",
    facebook: "https://www.facebook.com/david.skolnik.96",
    specialties: ["Personal Training", "Powerlifting", "Pain Free Performance", "Athletic Coaching"],
    certifications: [
      "Doctor of Physical Therapy",
      "Pain Free Performance Specialist",
      "Certified Powerlifting Coach",
    ],
    bio: "With over 7 years as a Doctor of Physical Therapy and Powerlifting Coach, I've trained athletes from their twenties to fifties. I've competed across federations in Oregon and Arizona, culminating in the IPF World's in Costa Mesa, CA in 2021.",
    passion: "My own recovery from back surgery and herniated discs has emphasized longevity in my coaching. Celebrating my athletes as they set state records in Arizona, I'm driven by their achievements and growth.",
    community: "I've immersed myself in the local fitness scene, working from the YMCA to as a freelance trainer in major cities. I am excited to be part of your fitness journey in this vibrant community.",
    schema: {
      jobTitle: "Doctor of Physical Therapy & Powerlifting Coach",
      sameAs: ["https://www.instagram.com/dr.davidskolnik.dpt/"],
    },
  },
  {
    id: "cam",
    name: "Cameron Dowling",
    title: "Personal Trainer, Group Fitness Coach, Master Kettlebell Trainer (RKC)",
    image: "/images/cam-dowling.webp",
    alt: "Cameron Dowling, master kettlebell trainer at The Gym of Tucson",
    imageWidth: 600,
    imageHeight: 750,
    instagram: "https://www.instagram.com/camdowling97/",
    instagramHandle: "@camdowling97",
    facebook: null,
    specialties: ["Personal Training", "Power Lifting", "Mobility Training", "Kettlebell Specialist"],
    certifications: [
      "ACE CPT",
      "RKC",
      "Level 1 USA Weightlifting Coach",
    ],
    bio: "Cameron has been deeply committed to fitness since high school, excelling in sports like soccer and golf and achieving competitive success in Olympic weightlifting.",
    passion: "As a Master Kettlebell Trainer through the R.K.C., Cameron specializes in strength training and takes pride in helping clients build confidence both in the gym and in their daily lives.",
    community: "Beyond personal training and group instruction, Cameron is pursuing a Master's in Clinical Mental Health Counseling at Grand Canyon University, aiming to support their community in achieving both physical and mental well-being.",
    schema: {
      jobTitle: "Personal Trainer & Kettlebell Specialist",
      sameAs: ["https://www.instagram.com/camdowling97/"],
    },
  },
  {
    id: "angie",
    name: "Angie Moore",
    title: "Personal Trainer, Group Fitness Coach, Pelvic Floor Specialist",
    image: "/images/angela-moore.webp",
    alt: "Angie Moore, personal trainer and pelvic floor specialist at The Gym of Tucson",
    imageWidth: 600,
    imageHeight: 750,
    instagram: "https://www.instagram.com/moore4urlife/",
    instagramHandle: "@moore4urlife",
    facebook: null,
    specialties: ["Personal Training", "Power Lifting", "Mobility Training", "Pelvic Floor Balance"],
    certifications: [
      "NASM CPT",
      "ISSA Nutrition Specialist",
      "Pain-Free Performance Certification",
      "Programming Around Pain Certification",
    ],
    bio: "As a certified personal trainer, nutrition coach, and pelvic floor balance specialist, I bring my passion for fitness and wellness to help others build strength, improve their nutrition, and achieve their goals. My journey as a busy mom and coach fuels my dedication to guiding others through realistic, sustainable lifestyle changes.",
    passion: "Empowered by the belief that proper nutrition and strength training can transform lives, I'm committed to helping you feel stronger, healthier, and more confident — both inside and outside the gym.",
    community: "When I'm not coaching, you'll find me in the gym working on my own fitness goals, taking on new workout challenges that push my body to the limit. I love testing my commitment and embracing those breakthrough moments, sharing this journey with my husband and involving my kids in staying active.",
    schema: {
      jobTitle: "Personal Trainer & Pelvic Floor Specialist",
      sameAs: ["https://www.instagram.com/moore4urlife/"],
    },
  },
];
